version: '3.8'

services:
  bi-part-app-dev:
    build:
         context: .
         dockerfile: dockerfile.dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - ./public:/app/public
    ports:
      - '3021:3021'
    env_file:
      - .env
